version: "1"
rules:
  - base: lineage-15.1
    upstream: LineageOS:lineage-15.1
    mergeMethod: hardreset
  - base: lineage-17.1
    upstream: LineageOS:lineage-17.1
    mergeMethod: hardreset
  - base: lineage-18.1
    upstream: LineageOS:lineage-18.1
    mergeMethod: hardreset
